common:
  start_date: "2010-09-18 00:00" # Default start, can be overridden by CLI
  end_date: "2010-09-20 00:00" # Default end 
  time_step_hours: 1 # For GFS or ERA5 range
  output_dir: "data/era5"

datasets:
  era5_surface:
    type: "cds"
    dataset_name: "reanalysis-era5-single-levels"
    product_type: "reanalysis"
    format: "grib"
    variable:
      - "10m_u_component_of_wind"     # u_s10m
      - "10m_v_component_of_wind"     # v_s10m
      - "2m_dewpoint_temperature"     # d_s2m
      - "2m_temperature"              # t_s2m
      - "mean_sea_level_pressure"     # msl_sfc
      - "sea_surface_temperature"     # sst_sea
      - "surface_pressure"            # sp_sfc
      - "total_precipitation"         # tp_sfc
      - "surface_thermal_radiation_downwards" # ssrd_sfc
      - "top_net_thermal_radiation"   # ttr_sfc
      - "boundary_layer_height"       # blh
      - "geopotential"                # hgt
      - "land_sea_mask"               # lsm
      - "total_column_water"          # tcw
      - "total_column_water_vapour"   # tcwv
      - "100m_u_component_of_wind"    # u_s100m
      - "100m_v_component_of_wind"            # v_s100m

  era5_upper:
    type: "cds"
    dataset_name: "reanalysis-era5-pressure-levels"
    product_type: "reanalysis"
    format: "grib"
    variable:
      - "geopotential"                        # z_50hPa
      - "relative_humidity"                   # r_50hPa
      - "specific_cloud_ice_water_content"    # ciwc_50hPa
      - "specific_cloud_liquid_water_content" # clwc_50hPa
      - "specific_humidity"                   # q_50hPa
      - "specific_rain_water_content"         # crwc_50hPa
      - "specific_snow_water_content"         # cswc_50hPa
      - "temperature"                         # t_50hPa
      - "u_component_of_wind"                 # u_50hPa
      - "v_component_of_wind"                 # v_50hPa
      - "vertical_velocity"                   # omg_50hPa
    pressure_level:
      - "50"
      - "100"
      - "150"
      - "200"
      - "250"
      - "300"
      - "350"
      - "400"
      - "500"
      - "600"
      - "700"
      - "850"
      - "925"
      - "1000"

  era5_pangu:
    type: "cds_pangu_combined"
    surface: "era5_pangu_surface"
    upper: "era5_pangu_upper"

  era5_pangu_surface:
    type: "cds_pangu_surface"
    dataset_name: "reanalysis-era5-single-levels"
    product_type: "reanalysis"
    format: "netcdf"
    variable:
      - "mean_sea_level_pressure"
      - "10m_u_component_of_wind"
      - "10m_v_component_of_wind"
      - "2m_temperature"
    grid: [0.25, 0.25]

  era5_pangu_upper:
    type: "cds_pangu_upper"
    dataset_name: "reanalysis-era5-pressure-levels"
    product_type: "reanalysis"
    format: "netcdf"
    variable:
      - "geopotential"
      - "specific_humidity"
      - "temperature"
      - "u_component_of_wind"
      - "v_component_of_wind"
    pressure_level:
      - "1000"
      - "925"
      - "850"
      - "700"
      - "600"
      - "500"
      - "400"
      - "300"
      - "250"
      - "200"
      - "150"
      - "100"
      - "50"
    grid: [0.25, 0.25]

  gfs_upper:
    type: "gdex"
    dataset_name: "ds083.3"
    param_template: "{vars}"
    level_template: "ISBL:{levels}"
    variables:
      - "TMP" # Temperature
      - "UGRD" # U Wind
      - "VGRD" # V Wind
      - "HGT" # Geopotential Height
      - "RH" # Relative Humidity
      - "VVEL" # Vertical Velocity (Pa/s)
      - "SPFH" # Specific Humidity
    levels:
      - "1000"
      - "925"
      - "850"
      - "700"
      - "600"
      - "500"
      - "400"
      - "300"
      - "250"
      - "200"
      - "150"
      - "100"
      - "50"

  gfs_surface_2m:
    type: "gdex"
    dataset_name: "ds083.3"
    param_template: "{vars}"
    level_template: "HTGL:2"
    variables:
      - "TMP" # 2m Temperature
      - "DPT" # 2m Dewpoint

  gfs_surface_10m:
    type: "gdex"
    dataset_name: "ds083.3"
    param_template: "{vars}"
    level_template: "HTGL:10"
    variables:
      - "UGRD" # 10m U Wind
      - "VGRD" # 10m V Wind

  gfs_surface_misc:
    type: "gdex"
    dataset_name: "ds083.3"
    param_template: "{vars}"
    # PRMSL implies MSL level. APCP usually Surface. PRES usually Surface.
    # Grouping these is risky without confirming they all accept 'SFC' or no level.
    # PRMSL usually needs MSL level if strict.
    # We'll split PRMSL to be safe.
    level_template: "SFC:0"
    variables:
      - "PRES" # Surface Pressure
      - "HGT" # Surface Geopotential (Orography)
      - "APCP" # Total Precipitation

  gfs_msl:
    type: "gdex"
    dataset_name: "ds083.3"
    param_template: "{vars}"
    level_template: "MSL"
    variables:
      - "PRMSL" # Mean Sea Level Pressure
